apiVersion: v1
kind: Service
metadata:
    name: "intertechdemo-0f73"
    labels:
        app: "intertechdemo-0f73"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "intertechdemo-0f73"