on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: intertechdemo.azurecr.io
        username: ${{ secrets.acr_intertechdemo_username }}
        password: ${{ secrets.acr_intertechdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/dotnet/nginx" -f  "dotnet/nginx/Dockerfile" -t intertechdemo.azurecr.io/intertechdemo:${{ github.sha }} --label dockerfile-path=dotnet/nginx/Dockerfile
        docker push intertechdemo.azurecr.io/intertechdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_intertechdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dotnet | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dotnet`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dotnet
        container-registry-url: intertechdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_intertechdemo_username }}
        container-registry-password: ${{ secrets.acr_intertechdemo_password }}
        secret-name: intertechdemdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dotnet
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          intertechdemo.azurecr.io/intertechdemo:${{ github.sha }}
        imagepullsecrets: |
          intertechdemdockerauth
